---
version: '3'

services:
  myapp:
    container_name: myapp
    image: nginxdemos/hello
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`${MYAPP_HOSTNAME}`)"
      - "traefik.http.routers.myapp.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.myapp.tls=true"
      - "traefik.http.routers.myapp.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.services.myapp.loadbalancer.server.port=80"
